// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://htksawtpoaifhednjvsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0a3Nhd3Rwb2FpZmhlZG5qdnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDcwNzgsImV4cCI6MjA2OTk4MzA3OH0.nxevwkzQ9QCmImw0hJrrlC3FMz0bl_jf-uQpsbr6PoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);